#!/bin/sh

mount -t proc proc /proc
mount -t sysfs none /sys

echo
echo "*** mini-linux-distro init ***"
echo "build with make, musl-libc, busybox"
echo "Enjoy the simplicity!"
echo

# https://busybox.net/FAQ.html#job_control
mknod /dev/ttyS0 c 4 64
setsid sh -c 'exec sh </dev/ttyS0 >/dev/ttyS0 2>&1'
